web:
  build: ./docker/web
  ports:
   - '8000:80' 
  volumes:
   - ./crossUp:/var/www/html
   - ./docker/web/000-default.conf:/etc/apache2/sites-available/000-default.conf
  links:
   - mysql
mysql:
  image: mysql:latest
  ports:
   - '33333:3306'
  volumes:
   - ./docker/mysql:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: pass
